---
name: "Image: Rebuild"

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "!apps/**/metadata.json"
      - "!apps/**/README.md"

jobs:
  get-changes:
    name: Collect changes
    runs-on: ubuntu-latest
    outputs:
      addedOrModifiedImages: ${{ steps.collect-changes.outputs.addedOrModifiedImages }}
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

  determine-images:
    name: Determine Images to Build
    runs-on: ubuntu-latest
    needs: ["get-changes"]
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: ${{ needs.get-changes.outputs.addedOrModifiedImages }} != '[]'
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Fetch modified images
        id: get-changed
        shell: bash
        run: |
          output="$(.github/scripts/determine_changes.py "${{ inputs.app }}" "${{ inputs.debian_version }}")
          echo "changes=${output}" >> $GITHUB_OUTPUT
          echo "Changes:\n ${output}"

  images-build:
    uses: samipsolutions/containers/.github/workflows/action-image-build.yaml@main
    needs:
      - determine-images
    with:
      imagesToBuild: "${{ needs.determine-images.outputs.matrix }}"
      pushImages: "true"
    secrets: inherit
