---
name: "Image: Rebuild"

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "!apps/**/metadata.json"
      - "!apps/**/README.md"

jobs:
  get-changes:
    name: Collect changes
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      addedOrModifiedImages: ${{ steps.collect-changes.outputs.addedOrModifiedImages }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

  determine-images:
    name: Determine Images to Build
    runs-on: buildjet-2vcpu-ubuntu-2204
    needs: ["get-changes"]
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: ${{ needs.get-changes.outputs.addedOrModifiedImages }} != '[]'
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - name: Fetch modified images
        id: get-changed
        shell: bash
        run: |
          declare -a changes_array=()
          while read -r app
          do
            while read -r channel
            do
              if [ -z "$debian_version" ] || [ "$debian_version" == "null" ]; then
                change="$(./.github/scripts/generate_modified_json.py $app $channel)"
              else
                change="$(./.github/scripts/generate_modified_json.py $app $channel $debian_version)"
              fi
              changes_array+=($change)
            done < <(jq -r '.channels[] | .name' "./apps/$app/metadata.json")
          done < <(echo '${{ needs.get-changes.outputs.addedOrModifiedImages }}' | jq --raw-output -c '.[]')

          output="$(jo -a ${changes_array[*]})"
          echo "changes=${output}" >> $GITHUB_OUTPUT
          echo "Changes:\n ${output}"

  images-build:
    uses: samipsolutions/containers/.github/workflows/action-image-build.yaml@main
    needs:
      - determine-images
    with:
      imagesToBuild: "${{ needs.determine-images.outputs.matrix }}"
      pushImages: "true"
    secrets: inherit
