---
name: "Manual Release"

concurrency:
  group: container-release
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App (ex: radarr)"
        default: ""
        required: true
      channels:
        description: "Channels (ex: master,develop)"
        default: ""
        required: false
      push:
        description: "Push"
        default: "false"
        required: true

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  determine-images:
    name: Determine Images to Build
    runs-on: ubuntu-latest
    outputs:
      imagesToBuild: ${{ steps.determine-images.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Determine images to build
        id: determine-images
        shell: bash
        run: |
          if [ "${{ inputs.app }}" = "ALL" ]; then
            output=$(./.github/scripts/fetch.py all)
            echo "changes=${output}" >> $GITHUB_OUTPUT
            echo "Changes:\n ${output}"
          else
           output=$(.github/scripts/determine_images.py "${{ inputs.app }}" "${{ inputs.channels }}")
           echo "changes=${output}" >> $GITHUB_OUTPUT
           echo "Changes:\n ${output}"
          fi

  images-build:
    uses: ./.github/workflows/action-image-build.yaml
    if: needs.determine-images.outputs.imagesToBuild != '[]'
    needs: ["determine-images"]
    with:
      imagesToBuild: "${{ needs.determine-images.outputs.imagesToBuild }}"
      pushImages: "${{ github.event.inputs.push }}"
    secrets: inherit
