---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Scheduled Release

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appsToBuild:
        description: App(s) to build
        required: false
        type: string
        default: all
      force:
        description: Force rebuild
        type: boolean
        default: false
        required: true
  schedule:
    - cron: "0 * * * *"

jobs:
  simple-checks:
    name: Simple Checks
    uses: onedr0p/containers/.github/workflows/simple-checks.yaml@main

  build-images:
    name: Build Images
    needs: simple-checks
    uses: ./.github/workflows/build-images.yaml
    permissions:
      contents: read
      packages: write
    with:
      appsToBuild: ${{ inputs.appsToBuild }}
      force: ${{ inputs.force == true }}
      pushImages: true
      sendNotifications: true
    secrets:
      BOT_APP_ID: "${{ secrets.BOT_APP_ID }}"
      BOT_APP_PRIVATE_KEY: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
